      # ПЕРВЫЙ ВАРИАНТ УСТАНАВЛИВАЕТСЯ СЮДА:
      - name: Accept Android SDK Licenses
        uses: android-actions/setup-android@v3
        with:
          packages: platform-tools # Указываем только живой пакет, без 'tools'
